name: Deploy Databricks Notebooks

on:
  push:
    branches:
      - main  # Active when something changes in 'main'.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Git Integration in Databricks
        run: |
          echo "Checking Databricks Git Integration..."
          # Ensure that Workspace was integrated to Git repo.
      
      - name: Sync Databricks with Git Repository
        run: |
          echo "Triggering Git Sync in Databricks Workspace..."
